# Generated by Django 6.0.6 on 2026-07-10 18:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="campaign",
            old_name="end_datetime",
            new_name="end_time",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="first_send_datetime",
        ),
        migrations.AddField(
            model_name="campaign",
            name="start_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Рассылка не начнется раньше этого времени.",
                verbose_name="Дата и время начала отправки",
            ),
            preserve_default=False,
        ),
    ]
