# Generated by Django 6.0.6 on 2026-06-09 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0002_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "first_send_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="Будет заполнено автоматически при первой отправке.",
                        null=True,
                        verbose_name="Дата и время первой отправки",
                    ),
                ),
                ("end_datetime", models.DateTimeField(verbose_name="Дата и время окончания отправки")),
                (
                    "status",
                    models.CharField(
                        choices=[("Создана", "Создана"), ("Запущена", "Запущена"), ("Завершена", "Завершена")],
                        default="Создана",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="mailer.message", verbose_name="Сообщение"
                    ),
                ),
                ("recipients", models.ManyToManyField(to="mailer.recipient", verbose_name="Получатели")),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
