# Generated by Django 6.0.6 on 2026-07-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0002_rename_end_datetime_campaign_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="start_time",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Рассылка не начнется раньше этого времени.",
                verbose_name="Дата и время начала отправки",
            ),
        ),
    ]
