# Generated by Django 6.0.6 on 2026-07-10 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0003_alter_campaign_start_time"),
    ]

    operations = []
