# Generated by Django 6.0.6 on 2026-07-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0004_auto_20260710_2203"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="start_time",
            field=models.DateTimeField(
                help_text="Рассылка не начнется раньше этого времени.", verbose_name="Дата и время начала отправки"
            ),
        ),
    ]
