# Generated by Django 6.0.6 on 2026-07-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailer", "0005_alter_campaign_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="first_send_datetime",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Дата и время первой отправки"
            ),
        ),
    ]
